# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 14:13
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('memory', models.IntegerField(default=9999999999)),
                ('time', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('school', models.CharField(default='', max_length=55)),
                ('img', models.CharField(default='', max_length=100)),
                ('birthyear', models.CharField(default='', max_length=30)),
                ('city', models.CharField(default='', max_length=30)),
                ('solved', models.IntegerField(default=0)),
            ],
        ),
    ]
