# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_problem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=30)),
                ('problems', models.TextField(default='')),
            ],
        ),
    ]
