# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161125_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='synced',
            old_name='data',
            new_name='date',
        ),
    ]
