# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161125_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=30)),
                ('follows', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
